language: perl
#group:    stable
#dist:     trusty
#os:       linux

perl:
  - '5.8'
  - '5.24'
  - '5.26'

script:
  - cpanm --notest Test::Pod
  - cpanm --notest Test::Perl::Critic
  - perl Makefile.PL
  - TEST_AUTHOR=1 make test
