# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SMTP-OneLiner
version:      1.2.0
version_from: OneLiner.pm
installdirs:  site
requires:
    Net::SMTP:                     

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
